### ISSUE TITLE
Compilation with CUDA 11.8 fails with the latest Vidual Studio 2022 (17.0)

### ISSUE THREAD

**Issue by martinResearch** [cupy/cupy#8578]
### Description

**Problem**

I am getting a compilation error when compiling CUDA code with cupy and CUDA 11.8 since a new version of the visual studio compiler has been released (17.0)
the error is 
```
C:\Miniconda\envs\cupy_project\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
 E               nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
```
The problem is discussed on the NVidida form [here](https://forums.developer.nvidia.com/t/problems-with-latest-vs2022-update/294150/2)

**Solution**
It is mentioned  [here](https://forums.developer.nvidia.com/t/problems-with-latest-vs2022-update/294150/2) that switching to  CUDA 12.5 could solve the problem. However it is not possible to do that swithc for my project due to other dependencies. 
As a mitigation we could add the flag `allow-unsupported-compiler` in the function [compile_using_nvcc`](https://github.com/cupy/cupy/blob/aa9b743d07eacbfc7d715369b762879c3c362d9e/cupy/cuda/compiler.py#L341)

### To Reproduce

```py
# Write the code here
```

### Installation

create a pyhon conda environment using the environment file 
```
name:  runtime
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python=3.10
  - cuda-version==11.8
  - cuda-toolkit=11.8  
  - cudnn==8.9.7.29
  - pip:
    - -r requirements.txt

variables:
  OPENCV_IO_ENABLE_OPENEXR: "1"
  CUDA_PATH: ""
  CUDA_HOME: ""
```
then install cupy-cuda11x==12.3.0
```
pip install cupy-cuda11x==12.3.0
```

### Environment

Windows. 
Visual studio  2022  version 17.0
